version: "3"
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"

  tonoback:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    entrypoint: /bin/sh -c "npx prisma migrate dev && npm run start"